easy_admin:
    disabled_actions: ['edit', 'new']
    site_name: 'ArtWonder Administración'
    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
        Usuario:
            class: App\Entity\Usuario

        Marcas:
            class: App\Entity\MarcaAutor

        WondArts:
            class: App\Entity\WondArt
    user:
        name_property_path: 'nombre'
        display_avatar: false