easy_admin:
    site_name: 'ArtWonder Administration'
    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
        Usuario:
            class: App\Entity\Usuario
    user:
        name_property_path: 'nombre'
        display_avatar: false